name: 🔗 GHA
on:
  workflow_dispatch:

  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
      - "**/*.png"
      - ".github/ISSUE_TEMPLATE/*"
      - ".github/CODEOWNERS"
      - "project/demo/*"
  push:
    branches:
      - "main"
    paths-ignore:
      - "**/*.md"
      - "**/*.png"
      - "**/LICENSE"
      - ".github/ISSUE_TEMPLATE/*"
      - ".github/CODEOWNERS"
      - "project/demo/*"

env:
  GODOT_VERSION: 4.2.1

jobs:
  
  gdextension-build:
    name: ⚙️ GDExtension
    uses: ./.github/workflows/gdextension.yml
    with:
      fullbuild: true
      godot_version: 4.2.1
  
  gdextension-unit-tests:
    name: ⚙️ GDExtension Unit Tests
    needs: gdextension-build
    uses: ./.github/workflows/gdextension-unit-tests.yml
    with:
      godot_version: 4.2.1